# Generated by Django 4.2.7 on 2026-05-16 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_user_is_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
    ]
