# Generated by Django 4.2.7 on 2026-05-16 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_page',
            field=models.URLField(blank=True, default='', help_text='Facebook page URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_maps_link',
            field=models.URLField(blank=True, default='', help_text='Google Maps embed or directions link for your location'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='messenger_link',
            field=models.URLField(blank=True, default='', help_text='Full Facebook Messenger URL, e.g. https://m.me/your_page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(blank=True, default='', help_text='WhatsApp number in international format without +, e.g. 8801712345678', max_length=20),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='business_name',
            field=models.CharField(default='Print-Edge', max_length=100),
        ),
    ]
