# Generated by Django 4.2.7 on 2026-05-16 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sitesettings_social_links_and_branding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='max_login_attempts',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='session_timeout_minutes',
        ),
    ]
