# Generated by Django 4.2.7 on 2026-05-25 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_user_is_email_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='business_address',
            field=models.TextField(default='Default delivery location: Gono Bishwabidyalay (convenience point only). Not affiliated with Gono Bishwabidyalay.'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Profile Photo URL'),
        ),
    ]
