# Generated by Django 4.2.0 on 2026-05-25 10:33
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_sitesettings_business_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(max_length=500, blank=True, null=True, verbose_name='Profile Photo URL'),
        ),
    ]