# Generated by Django 4.2.30 on 2026-05-31 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_studioservice_order_studio_services_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='studio_services_data',
        ),
        migrations.RemoveField(
            model_name='order',
            name='studio_services_price',
        ),
        migrations.AddField(
            model_name='order',
            name='payment_rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='payment_screenshot',
            field=models.ImageField(blank=True, null=True, upload_to='payment-screenshots/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('unpaid', 'Unpaid'), ('partial', 'Partial'), ('pending_review', 'Pending Review'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('refunded', 'Refunded')], default='unpaid', max_length=20),
        ),
    ]
