# Generated by Django 4.2.30 on 2026-06-01 06:00

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_add_payment_screenshot'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ('objects', core.models.EmailUserManager()),
        ],
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
