# Generated by Django 4.2.30 on 2026-06-02 11:32

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_emaillog_sitesettings_require_email_verification_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('subject', models.CharField(max_length=255)),
                ('html_body', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(core.models.DualWriteMixin, models.Model),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='email_from_name',
            field=models.CharField(default='PrintEdge', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='send_email_on_admin_approval',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='send_email_on_order_placed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='send_email_on_payment_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='send_email_on_payment_rejected',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='send_email_on_registration',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='send_email_on_status_change',
            field=models.BooleanField(default=True),
        ),
    ]
