# Generated by Django 4.2.30 on 2026-06-04 16:51

import core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_create_premium_email_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('discount_type', models.CharField(choices=[('percent', 'Percent'), ('flat', 'Flat Amount')], max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=2, max_digits=8)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('max_uses', models.IntegerField(default=100)),
                ('used_count', models.IntegerField(default=0)),
                ('valid_from', models.DateTimeField(default=django.utils.timezone.now)),
                ('valid_to', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            bases=(core.models.DualWriteMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='order',
            name='promo_code',
        ),
        migrations.AddField(
            model_name='pricingrule',
            name='inventory_item',
            field=models.ForeignKey(blank=True, help_text='Linked inventory item for auto-deduction', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.inventoryitem'),
        ),
        migrations.AddField(
            model_name='user',
            name='custom_permissions',
            field=models.JSONField(blank=True, help_text='Overrides role permissions if set.', null=True),
        ),
        migrations.DeleteModel(
            name='PromoCode',
        ),
        migrations.AddField(
            model_name='coupon',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.coupon'),
        ),
    ]
