# Generated by Django 4.2.30 on 2026-06-04 19:31

import core.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_coupon_created_at_alter_coupon_created_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('category', models.CharField(choices=[('Printing', 'Printing'), ('Photo', 'Photo'), ('Binding', 'Binding'), ('Lamination', 'Lamination'), ('Stationery', 'Stationery'), ('Custom', 'Custom')], max_length=100)),
                ('specs', models.JSONField(blank=True, default=dict, help_text='Dynamic specs: paper_size, gsm, color_type, etc.')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['category', 'name'],
            },
            bases=(core.models.DualWriteMixin, models.Model),
        ),
        migrations.CreateModel(
            name='ServiceVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('additional_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('specs', models.JSONField(blank=True, default=dict, help_text='Matches service specs format')),
                ('is_active', models.BooleanField(default=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='core.service')),
            ],
            options={
                'ordering': ['service', 'name'],
            },
            bases=(core.models.DualWriteMixin, models.Model),
        ),
        migrations.DeleteModel(
            name='StudioService',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='last_restocked',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='variant',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inventory_item', to='core.servicevariant'),
        ),
        migrations.AddField(
            model_name='servicevariant',
            name='stock',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicevariant',
            name='low_stock_threshold',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=10),
        ),
        migrations.AddField(
            model_name='servicevariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
        ),
    ]