# Generated by Django 4.2.30 on 2026-06-05 09:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_service_servicevariant_delete_studioservice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assigned_to',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['operator', 'manager', 'admin', 'super_admin']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
