# Generated by Django 4.2.30 on 2026-06-05 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_fix_coupon_valid_to'),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, migrations.RunPython.noop),
    ]
