# Generated by Django 4.2.30 on 2026-06-05 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_ensure_base_price_column'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='specs',
        ),
        migrations.RemoveField(
            model_name='servicevariant',
            name='additional_price',
        ),
        migrations.AddField(
            model_name='service',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='servicevariant',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Price for this variant (0 = inherits service base_price)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='service',
            name='category',
            field=models.CharField(choices=[('printing', 'Printing'), ('photo', 'Photo'), ('binding', 'Binding'), ('lamination', 'Lamination'), ('stationery', 'Stationery'), ('custom', 'Custom')], max_length=100),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='low_stock_threshold',
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='specs',
            field=models.JSONField(blank=True, default=dict, help_text='Arbitrary key-value pairs like paper_size, gsm, etc.'),
        ),
        migrations.AlterField(
            model_name='servicevariant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
