# Generated by Django 4.2.30 on 2026-06-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_service_model_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
