# Generated by Django 4.2.30 on 2026-06-06 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_variant_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='requires_file',
            field=models.BooleanField(default=False, help_text='If checked, customers must upload a file when ordering this service.'),
        ),
    ]
