# Generated by Django 4.2.30 on 2026-06-09 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_service_requires_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='service',
            field=models.ForeignKey(blank=True, help_text='Selected service for this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.service'),
        ),
        migrations.AddField(
            model_name='order',
            name='variant',
            field=models.ForeignKey(blank=True, help_text='Selected variant/service option for this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='core.servicevariant'),
        ),
    ]
