# Generated by Django 4.2.30 on 2026-06-09 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_migrate_pricing_to_servicevariant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingRule',
        ),
    ]
